# -*- coding: utf-8 -*-
"""v1.13 (turunan 11).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyzW6QhrWHf0LGZ1WC5zROIgGFL3Da9j

**📌 1️⃣ IMPORT LIBRARY**
"""

import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score

"""**📌 2️⃣ SIMULASI DATA**"""

np.random.seed(42)

rows = 5000

data = pd.DataFrame({
    "year": np.random.choice([2024, 2025], rows),
    "month": np.random.randint(1, 13, rows),
    "total_devices": np.random.randint(5, 25, rows),
    "total_watt_installed": np.random.randint(800, 5000, rows),
    "avg_usage_hours": np.random.uniform(3, 12, rows),
    "last_month_kwh": np.random.uniform(150, 600, rows)
})

# Feature engineering
data["growth_kwh"] = np.random.uniform(-30, 30, rows)

data["avg_3_month_kwh"] = (
    data["last_month_kwh"]
    + np.random.uniform(-15, 15, rows)
)

data["total_kwh_current"] = (
    data["last_month_kwh"]
    + data["growth_kwh"]
    + (data["total_devices"] * 2)
)

# Target bulan depan
data["target_kwh_next_month"] = (
    data["total_kwh_current"]
    + np.random.uniform(-20, 20, rows)
)

# Simulasi tarif PLN
TARIF = 1444.7

data["target_bill_next_month"] = data["target_kwh_next_month"] * TARIF

data.head()

"""**📌 3️⃣ PILIH FEATURE & TARGET**"""

features = [
    "year",
    "month",
    "total_devices",
    "total_watt_installed",
    "avg_usage_hours",
    "last_month_kwh",
    "avg_3_month_kwh",
    "growth_kwh"
]

X = data[features]
y_kwh = data["target_kwh_next_month"]
y_bill = data["target_bill_next_month"]

"""**📌 4️⃣ SPLIT DATA**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y_kwh,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

"""**📌 5️⃣ TRAIN RANDOM FOREST**"""

# rows = 5000

# data = pd.DataFrame({
#     "year": np.random.choice([2024, 2025], rows),
#     "month": np.random.randint(1, 13, rows),
#     "total_devices": np.random.randint(5, 20, rows),
# })

# # watt per device rata-rata
# data["avg_device_watt"] = np.random.uniform(60, 250, rows)

# # total watt rumah
# data["total_watt_installed"] = data["total_devices"] * data["avg_device_watt"]

# # jam pemakaian per hari
# data["avg_usage_hours"] = np.random.uniform(3, 10, rows)

# # hari per bulan
# data["days_in_month"] = 30

# # konsumsi listrik realistis
# data["total_kwh_current"] = (
#     data["total_watt_installed"]
#     * data["avg_usage_hours"]
#     * data["days_in_month"]
# ) / 1000

data["growth_kwh"] = np.random.normal(0, 15, rows)
data["target_kwh_next_month"] = (
    data["total_kwh_current"]
    + data["growth_kwh"]
)

model_kwh = RandomForestRegressor(
    n_estimators=400,
    max_depth=8,
    min_samples_leaf=10,
    min_samples_split=20,
    random_state=42,
    n_jobs = -1
)

model_kwh.fit(X_train, y_train)

scores = cross_val_score(model_kwh, X, y_kwh, cv=5, scoring="r2")

print("Cross Validation R2:", scores)
print("Average R2:", scores.mean())

"""**📌 6️⃣ EVALUASI**"""

y_pred = model_kwh.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", rmse)
print("R2 Score:", r2_score(y_test, y_pred))

plt.figure(figsize=(6,6))

plt.scatter(y_test, y_pred, color="yellow", alpha=0.6, label="Prediction")

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    color="red",
    linestyle="--",
    label="Perfect Prediction"
)

plt.xlabel("Actual KWH")
plt.ylabel("Predicted KWH")
plt.title("Actual vs Predicted KWH")

plt.legend()
plt.show()

"""**📌 7️⃣ SIMPAN MODEL**"""

with open("electricity_model.pkl", "wb") as f:
    pickle.dump(model_kwh, f)

print("Model saved!")

"""**🎯 STEP 2 — TEST PREDIKSI MANUAL**"""

sample_input = pd.DataFrame([{
    "year": 2026,
    "month": 3,
    "total_devices": 12,
    "total_watt_installed": 2500,
    "avg_usage_hours": 7,
    "last_month_kwh": 350,
    "avg_3_month_kwh": 340,
    "growth_kwh": 10
}])

print(model_kwh.feature_names_in_)
print(sample_input.columns)

def predict_with_interval(model, input_df):

    preds = np.array([
        # tree.predict(input_df)[0]
        tree.predict(input_df.values)[0]
        for tree in model.estimators_
    ])

    mean = preds.mean()
    std = preds.std()

    lower = mean - 1.28 * std
    upper = mean + 1.28 * std

    return mean, lower, upper

pred_kwh, lower_kwh, upper_kwh = predict_with_interval(
    model_kwh,
    sample_input
)

pred_bill = pred_kwh * 1444.7
lower_bill = lower_kwh * 1444.7
upper_bill = upper_kwh * 1444.7

print("Predicted KWH:", pred_kwh)
print("Predicted Bill:", pred_bill)


print("Predicted KWH:", round(pred_kwh, 2))
print("95% CI KWH:", round(lower_kwh, 2), "-", round(upper_kwh, 2))

print("Predicted Bill:", round(pred_bill, 2))
print("95% CI Bill:", round(lower_bill, 2), "-", round(upper_bill, 2))