# -*- coding: utf-8 -*-
"""v3 - deepseek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12TRMSwByQrP0s58kTIi3mTYb8EgMtA6B
"""

# ============================================
# ELECTRICITY BILL PREDICTION - ENHANCED VERSION
# ============================================

import calendar
import os
import warnings
warnings.filterwarnings('ignore')

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, GridSearchCV, TimeSeriesSplit
from sklearn.preprocessing import StandardScaler, RobustScaler
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

# ============================================
# KONFIGURASI
# ============================================
DATA_PATH = "training_data.csv"
MODEL_PATH = "electricity_bill_model_enhanced.pkl"
RANDOM_STATE = 42

# Fitur yang lebih lengkap
FEATURE_COLUMNS = [
    "bill_amount",
    "bill_lag_1",
    "bill_lag_2",
    "bill_lag_3",
    "bill_lag_4",
    "bill_rolling_avg_3",
    "bill_rolling_avg_6",
    "bill_mom_change",
    "estimated_kwh",
    "estimated_kwh_lag_1",
    "total_duration_hours",
    "total_power_watt",
    "active_device_count",
    "month",
    "month_sin",
    "month_cos",
    "quarter",
    "is_holiday_season",
    "is_ramadan_effect",
    "days_in_month",
    "avg_daily_kwh",
    "efficiency_score",
]

# ============================================
# DATA GENERATION LEBIH REALISTIS
# ============================================
def calculate_estimated_kwh(power_watt, duration_hours, days):
    return power_watt * duration_hours * days / 1000


def get_seasonal_factor(month, year):
    """Faktor musiman yang lebih realistis untuk listrik di Indonesia"""
    # Musim kemarau (Apr-Sep) -> AC lebih sering -> tagihan naik
    # Musim hujan (Okt-Mar) -> tagihan cenderung turun
    dry_season = month in [4, 5, 6, 7, 8, 9]

    # Puncak kemarau (Juli-Agustus)
    peak_dry = month in [7, 8]

    # Faktor dasar
    if peak_dry:
        base_factor = 1.15
    elif dry_season:
        base_factor = 1.05
    else:
        base_factor = 0.95

    # Efek Ramadhan (biasanya naik ~15-20%)
    # Simulasi sederhana: bulan 3-4 (Maret-April)
    ramadan_factor = 1.18 if month in [3, 4] else 1.0

    # Efek liburan Desember
    holiday_factor = 1.12 if month == 12 else 1.0

    return base_factor * ramadan_factor * holiday_factor


def create_realistic_training_data(path=DATA_PATH, households=200, months=36):
    """Membuat data training yang lebih realistis"""
    rng = np.random.default_rng(RANDOM_STATE)
    rows = []

    for household_id in range(1, households + 1):
        # Karakteristik unik setiap rumah
        household_type = rng.choice(["small", "medium", "large"], p=[0.3, 0.5, 0.2])

        if household_type == "small":
            base_bill = rng.uniform(150_000, 300_000)
            device_range = (3, 10)
            power_range = (60, 150)
            tariff_per_kwh = rng.uniform(1350, 1500)
        elif household_type == "medium":
            base_bill = rng.uniform(300_000, 600_000)
            device_range = (8, 18)
            power_range = (100, 220)
            tariff_per_kwh = rng.uniform(1400, 1550)
        else:  # large
            base_bill = rng.uniform(600_000, 1_200_000)
            device_range = (15, 30)
            power_range = (150, 350)
            tariff_per_kwh = rng.uniform(1450, 1650)

        # Trend kenaikan pemakaian per tahun (~3-8%)
        usage_growth_trend = rng.uniform(0.03, 0.08)

        previous_bill = base_bill
        previous_kwh = base_bill / tariff_per_kwh

        for idx in range(months):
            year = 2022 + idx // 12
            month = (idx % 12) + 1
            days = calendar.monthrange(year, month)[1]

            # Trend pertumbuhan pemakaian
            growth_factor = 1 + (idx / 12) * usage_growth_trend

            # Perangkat aktif (bervariasi berdasarkan waktu)
            if 9 <= month <= 17:  # Siang
                device_mult = 0.8
            elif 18 <= month <= 22:  # Malam puncak
                device_mult = 1.3
            else:  # Malam larut/pagi
                device_mult = 0.6

            active_device_count = int(rng.integers(device_range[0], device_range[1]) * device_mult)
            avg_power = rng.uniform(power_range[0], power_range[1])
            total_power_watt = active_device_count * avg_power

            # Durasi penggunaan (lebih lama di akhir pekan)
            is_weekend = (idx % 7) in [5, 6]
            if is_weekend:
                total_duration_hours = rng.uniform(6, 14)
            else:
                total_duration_hours = rng.uniform(4, 10)

            estimated_kwh = calculate_estimated_kwh(
                total_power_watt, total_duration_hours, days
            ) * growth_factor

            # Faktor musiman
            seasonal_factor = get_seasonal_factor(month, year)

            # Harga per kWh berfluktuasi
            tariff = tariff_per_kwh * (1 + rng.normal(0, 0.03))

            # Tagihan dari pemakaian
            device_bill = estimated_kwh * tariff

            # Komponen inertia (tagihan sebelumnya berpengaruh)
            inertia_weight = rng.uniform(0.4, 0.7)

            # Noise yang lebih realistis (standar deviasi proporsional)
            noise_std = max(15_000, device_bill * 0.05)
            noise = rng.normal(0, noise_std)

            # Tagihan akhir
            bill_amount = (inertia_weight * previous_bill +
                          (1 - inertia_weight) * device_bill * seasonal_factor +
                          noise)

            bill_amount = max(50_000, bill_amount)

            rows.append({
                "household_id": household_id,
                "year": year,
                "month": month,
                "days_in_month": days,
                "bill_amount": round(bill_amount, 2),
                "estimated_kwh": round(estimated_kwh, 3),
                "total_duration_hours": round(total_duration_hours, 2),
                "total_power_watt": round(total_power_watt, 2),
                "active_device_count": active_device_count,
                "household_type": household_type,
                "tariff_per_kwh": round(tariff, 2),
            })

            previous_bill = bill_amount
            previous_kwh = estimated_kwh

    df = pd.DataFrame(rows)
    df.to_csv(path, index=False)
    print(f"Dataset dengan {len(df)} baris berhasil dibuat di {path}")
    return df


def load_training_data(path=DATA_PATH):
    if not os.path.exists(path):
        print(f"{path} tidak ditemukan. Membuat dataset realistis...")
        return create_realistic_training_data(path)
    return pd.read_csv(path)

# ============================================
# FEATURE ENGINEERING YANG LEBIH KAYA
# ============================================
def engineer_features(df):
    """Feature engineering yang lebih komprehensif"""
    required = {
        "household_id", "year", "month", "days_in_month",
        "bill_amount", "estimated_kwh", "total_duration_hours",
        "total_power_watt", "active_device_count"
    }
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Kolom training_data.csv kurang: {sorted(missing)}")

    data = df.copy()
    data = data.sort_values(["household_id", "year", "month"])

    group = data.groupby("household_id")["bill_amount"]
    group_kwh = data.groupby("household_id")["estimated_kwh"]

    # Lag features (4 lag untuk capture pola lebih panjang)
    for lag in [1, 2, 3, 4]:
        data[f"bill_lag_{lag}"] = group.shift(lag)
        data[f"estimated_kwh_lag_{lag}"] = group_kwh.shift(lag)

    # Rolling statistics
    data["bill_rolling_avg_3"] = group.transform(
        lambda x: x.shift(1).rolling(window=3).mean()
    )
    data["bill_rolling_avg_6"] = group.transform(
        lambda x: x.shift(1).rolling(window=6).mean()
    )
    data["bill_rolling_std_3"] = group.transform(
        lambda x: x.shift(1).rolling(window=3).std()
    )

    # Month-over-month change
    data["bill_mom_change"] = data.groupby("household_id")["bill_amount"].pct_change() * 100

    # Fitur siklik untuk bulan (encoding circular)
    data["month_sin"] = np.sin(2 * np.pi * data["month"] / 12)
    data["month_cos"] = np.cos(2 * np.pi * data["month"] / 12)
    data["quarter"] = data["month"].apply(lambda x: (x-1)//3 + 1)

    # Holiday season (Desember + Januari)
    data["is_holiday_season"] = data["month"].isin([12, 1]).astype(int)

    # Ramadan effect approximation (bulan 3-4)
    data["is_ramadan_effect"] = data["month"].isin([3, 4]).astype(int)

    # Efisiensi pemakaian (kWh per device per jam)
    data["avg_daily_kwh"] = data["estimated_kwh"] / data["days_in_month"]
    data["efficiency_score"] = data["estimated_kwh"] / (data["total_power_watt"] * data["total_duration_hours"] / 1000)
    data["efficiency_score"] = data["efficiency_score"].fillna(1).clip(0.5, 2)

    # Target
    data["next_month_bill"] = group.shift(-1)

    # Drop baris dengan nilai NaN
    required_features = FEATURE_COLUMNS + ["next_month_bill"]
    data_clean = data.dropna(subset=required_features)

    print(f"Feature engineering selesai: {len(data_clean)} baris tersisa")
    return data_clean

# ============================================
# TRAINING DENGAN HYPERPARAMETER TUNING
# ============================================
def train_model_enhanced(data, model_type="xgboost"):
    """Training dengan multiple model options dan tuning"""
    if data.empty:
        raise ValueError("Data training kosong setelah feature engineering")

    X = data[FEATURE_COLUMNS]
    y = data["next_month_bill"]

    # Standardisasi untuk model yang sensitif
    scaler = RobustScaler()
    X_scaled = scaler.fit_transform(X)

    # Split dengan mempertahankan urutan waktu
    train_size = int(0.8 * len(X))
    X_train, X_test = X_scaled[:train_size], X_scaled[train_size:]
    y_train, y_test = y.iloc[:train_size], y.iloc[train_size:]

    print(f"Training size: {len(X_train)}, Test size: {len(X_test)}")

    # Pilih model
    if model_type == "xgboost":
        model = XGBRegressor(
            n_estimators=500,
            max_depth=8,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=RANDOM_STATE,
            n_jobs=-1
        )
    elif model_type == "lightgbm":
        model = LGBMRegressor(
            n_estimators=500,
            max_depth=8,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=RANDOM_STATE,
            n_jobs=-1,
            verbose=-1
        )
    elif model_type == "randomforest":
        model = RandomForestRegressor(
            n_estimators=500,
            max_depth=12,
            min_samples_leaf=4,
            random_state=RANDOM_STATE,
            n_jobs=-1
        )
    else:
        model = GradientBoostingRegressor(
            n_estimators=200,
            max_depth=6,
            learning_rate=0.05,
            random_state=RANDOM_STATE
        )

    model.fit(X_train, y_train)

    # Predictions
    predictions = model.predict(X_test)

    # Metrics
    mae = mean_absolute_error(y_test, predictions)
    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    r2 = r2_score(y_test, predictions)

    # Mean Absolute Percentage Error (lebih intuitif)
    mape = np.mean(np.abs((y_test - predictions) / y_test)) * 100

    metrics = {
        "mae": float(mae),
        "rmse": float(rmse),
        "r2": float(r2),
        "mape": float(mape),
        "accuracy_percent": float(max(0, 100 - mape))
    }

    return model, scaler, metrics, X_test, y_test, predictions


def hyperparameter_tuning(data):
    """Grid search untuk menemukan hyperparameter terbaik"""
    print("\n=== HYPERPARAMETER TUNING ===")

    X = data[FEATURE_COLUMNS]
    y = data["next_month_bill"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=RANDOM_STATE
    )

    # Parameter grid untuk XGBoost
    param_grid = {
        'n_estimators': [300, 500],
        'max_depth': [6, 8, 10],
        'learning_rate': [0.03, 0.05, 0.07],
        'subsample': [0.7, 0.8, 0.9]
    }

    xgb = XGBRegressor(random_state=RANDOM_STATE, n_jobs=-1)

    grid_search = GridSearchCV(
        xgb, param_grid, cv=3,
        scoring='neg_mean_absolute_error',
        n_jobs=-1, verbose=0
    )
    grid_search.fit(X_train, y_train)

    print(f"Best parameters: {grid_search.best_params_}")
    print(f"Best MAE: {-grid_search.best_score_:.2f}")

    return grid_search.best_estimator_

# ============================================
# SAVE DAN LOAD MODEL
# ============================================
def save_model_enhanced(model, scaler, metrics, feature_importances=None, path=MODEL_PATH):
    artifact = {
        "model": model,
        "scaler": scaler,
        "feature_columns": FEATURE_COLUMNS,
        "metadata": {
            "target": "next_month_bill",
            "currency": "IDR",
            "metrics": metrics,
            "feature_importances": feature_importances,
            "version": "2.0"
        },
    }
    joblib.dump(artifact, path)
    return artifact


def predict_next_bill_enhanced(input_data, model_path=MODEL_PATH):
    artifact = joblib.load(model_path)
    model = artifact["model"]
    scaler = artifact["scaler"]
    feature_columns = artifact["feature_columns"]

    # Konversi input ke DataFrame
    if isinstance(input_data, dict):
        df = pd.DataFrame([input_data])
    else:
        df = input_data.copy()

    # Feature engineering untuk input
    if "estimated_kwh" not in df.columns:
        days = df["days"] if "days" in df.columns else 30
        df["estimated_kwh"] = calculate_estimated_kwh(
            df.get("total_power_watt", 1000),
            df.get("total_duration_hours", 6),
            days
        )

    # Hitung rolling avg jika ada lag
    if "bill_lag_1" in df.columns and "bill_rolling_avg_3" not in df.columns:
        df["bill_rolling_avg_3"] = df[["bill_lag_1", "bill_lag_2", "bill_lag_3"]].mean(axis=1)
        df["bill_rolling_avg_6"] = df[[f"bill_lag_{i}" for i in range(1, 7) if f"bill_lag_{i}" in df.columns]].mean(axis=1)

    # Fitur siklik
    if "month" in df.columns:
        df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
        df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

    # Cek missing columns
    missing = [col for col in feature_columns if col not in df.columns]
    if missing:
        # Isi dengan nilai default
        for col in missing:
            if col.startswith("bill_lag"):
                df[col] = df.get("bill_amount", 300000)
            elif col == "bill_rolling_avg_3":
                df[col] = df.get("bill_amount", 300000)
            elif col == "bill_mom_change":
                df[col] = 0
            elif col == "quarter":
                df[col] = (df.get("month", 6) - 1) // 3 + 1
            else:
                df[col] = 0

    X = df[feature_columns].astype(float)
    X_scaled = scaler.transform(X)

    prediction = model.predict(X_scaled)

    if len(prediction) == 1:
        return {
            "predicted_next_month_bill": round(float(max(prediction[0], 0)), 2),
            "confidence_lower": round(float(max(prediction[0] * 0.85, 0)), 2),
            "confidence_upper": round(float(prediction[0] * 1.15), 2),
        }

    return [
        {
            "predicted_next_month_bill": round(float(max(val, 0)), 2),
            "confidence_lower": round(float(max(val * 0.85, 0)), 2),
            "confidence_upper": round(float(val * 1.15), 2),
        }
        for val in prediction
    ]

# ============================================
# VISUALISASI DAN ANALISIS
# ============================================
def plot_results(y_test, predictions, metrics):
    """Visualisasi hasil prediksi"""
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    # Plot 1: Actual vs Predicted
    ax1 = axes[0, 0]
    ax1.scatter(y_test, predictions, alpha=0.5, edgecolors='k', linewidth=0.5)
    ax1.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
    ax1.set_xlabel("Actual Bill (IDR)")
    ax1.set_ylabel("Predicted Bill (IDR)")
    ax1.set_title(f"Actual vs Predicted (R² = {metrics['r2']:.3f})")

    # Plot 2: Residuals
    ax2 = axes[0, 1]
    residuals = y_test - predictions
    ax2.scatter(predictions, residuals, alpha=0.5, edgecolors='k', linewidth=0.5)
    ax2.axhline(y=0, color='r', linestyle='--')
    ax2.set_xlabel("Predicted Bill (IDR)")
    ax2.set_ylabel("Residuals (IDR)")
    ax2.set_title(f"Residual Plot (MAE = {metrics['mae']:.0f})")

    # Plot 3: Distribution of errors
    ax3 = axes[1, 0]
    ax3.hist(residuals, bins=50, edgecolor='black', alpha=0.7)
    ax3.axvline(x=0, color='r', linestyle='--')
    ax3.set_xlabel("Prediction Error (IDR)")
    ax3.set_ylabel("Frequency")
    ax3.set_title("Distribution of Prediction Errors")

    # Plot 4: Percentage error
    ax4 = axes[1, 1]
    pct_errors = (residuals / y_test) * 100
    pct_errors = pct_errors.clip(-50, 50)
    ax4.hist(pct_errors, bins=50, edgecolor='black', alpha=0.7)
    ax4.axvline(x=0, color='r', linestyle='--')
    ax4.set_xlabel("Percentage Error (%)")
    ax4.set_ylabel("Frequency")
    ax4.set_title(f"MAPE = {metrics['mape']:.1f}% | Accuracy = {metrics['accuracy_percent']:.1f}%")

    plt.tight_layout()
    plt.savefig("model_evaluation.png", dpi=150)
    plt.show()

    return fig


def plot_feature_importance(model, feature_columns):
    """Plot feature importance"""
    if hasattr(model, 'feature_importances_'):
        importances = model.feature_importances_

        # Sort descending
        indices = np.argsort(importances)[::-1]

        plt.figure(figsize=(12, 8))
        plt.title("Feature Importance")
        plt.bar(range(len(importances)), importances[indices])
        plt.xticks(range(len(importances)), [feature_columns[i] for i in indices], rotation=45, ha='right')
        plt.xlabel("Features")
        plt.ylabel("Importance")
        plt.tight_layout()
        plt.savefig("feature_importance.png", dpi=150)
        plt.show()

        # Print top 10 features
        print("\n=== TOP 10 FEATURES ===")
        for i in range(min(10, len(indices))):
            print(f"{i+1}. {feature_columns[indices[i]]}: {importances[indices[i]]:.4f}")

        return dict(zip(feature_columns, importances))
    return None

# ============================================
# MAIN EXECUTION
# ============================================
def main():
    print("=" * 50)
    print("ENHANCED ELECTRICITY BILL PREDICTION")
    print("=" * 50)

    # 1. Load atau generate data
    raw_data = load_training_data(DATA_PATH)
    print(f"\nData shape: {raw_data.shape}")
    print(raw_data.head())

    # 2. Feature engineering
    training_data = engineer_features(raw_data)
    print(f"\nAfter feature engineering: {training_data.shape}")

    # 3. Train model
    print("\n=== TRAINING MODEL ===")
    model, scaler, metrics, X_test, y_test, predictions = train_model_enhanced(
        training_data, model_type="xgboost"
    )

    print(f"\n=== MODEL PERFORMANCE ===")
    print(f"MAE: {metrics['mae']:,.2f} IDR")
    print(f"RMSE: {metrics['rmse']:,.2f} IDR")
    print(f"R²: {metrics['r2']:.4f} ({metrics['r2']*100:.2f}%)")
    print(f"MAPE: {metrics['mape']:.2f}%")
    print(f"Accuracy: {metrics['accuracy_percent']:.2f}%")

    # 4. Visualisasi
    plot_results(y_test, predictions, metrics)

    # 5. Feature importance
    feature_importance = plot_feature_importance(model, FEATURE_COLUMNS)

    # 6. Save model
    save_model_enhanced(model, scaler, metrics, feature_importance, MODEL_PATH)

    # 7. Test prediction
    print("\n=== TEST PREDICTION ===")
    sample = {
        "bill_amount": 4,
        "bill_lag_1": 330000,
        "bill_lag_2": 310000,
        "bill_lag_3": 300000,
        "bill_lag_4": 290000,
        "total_power_watt": 2200,
        "total_duration_hours": 6,
        "days": 30,
        "active_device_count": 12,
        "month": 6,
    }

    prediction = predict_next_bill_enhanced(sample)
    print(f"Sample input: {sample}")
    print(f"Prediction: {prediction}")

    return model, scaler, metrics

# ============================================
# BATCH PREDICTION UNTUK TESTING
# ============================================
def batch_prediction_test():
    """Testing batch prediction untuk berbagai skenario"""
    print("\n=== BATCH PREDICTION TEST ===")

    test_cases = [
        {"name": "Rumah kecil - bulan biasa",
         "data": {"bill_amount": 250000, "bill_lag_1": 240000, "bill_lag_2": 235000,
                  "bill_lag_3": 230000, "total_power_watt": 800, "total_duration_hours": 5,
                  "active_device_count": 5, "month": 6, "days": 30}},

        {"name": "Rumah besar - musim kemarau",
         "data": {"bill_amount": 800000, "bill_lag_1": 780000, "bill_lag_2": 750000,
                  "bill_lag_3": 720000, "total_power_watt": 3000, "total_duration_hours": 10,
                  "active_device_count": 20, "month": 8, "days": 31}},

        {"name": "Efek Ramadhan",
         "data": {"bill_amount": 450000, "bill_lag_1": 420000, "bill_lag_2": 400000,
                  "bill_lag_3": 390000, "total_power_watt": 1500, "total_duration_hours": 8,
                  "active_device_count": 12, "month": 4, "days": 30}},
    ]

    for case in test_cases:
        try:
            pred = predict_next_bill_enhanced(case["data"])
            print(f"\n{case['name']}:")
            print(f"  Prediksi bulan depan: Rp {pred['predicted_next_month_bill']:,.2f}")
            print(f"  Range estimasi: Rp {pred['confidence_lower']:,.2f} - Rp {pred['confidence_upper']:,.2f}")
        except Exception as e:
            print(f"Error untuk {case['name']}: {e}")

# ============================================
# RUN
# ============================================
if __name__ == "__main__":
    model, scaler, metrics = main()
    batch_prediction_test()

    print("\n" + "=" * 50)
    print("SUMMARY PENINGKATAN:")
    print("=" * 50)
    print("1. Dataset lebih realistis (200 rumah × 36 bulan)")
    print("2. Feature engineering lebih kaya (20+ fitur)")
    print("3. Circular encoding untuk bulan (sin/cos)")
    print("4. Rolling statistics (3 & 6 bulan)")
    print("5. Efficiency score & MOM change")
    print("6. XGBoost + scaling untuk performa lebih baik")
    print("7. Confidence interval untuk prediksi")
    print("8. Visualisasi lengkap untuk analisis")
    print(f"\nTarget akurasi: >70% (R² > 0.7)")
    print(f"Akurasi saat ini: {metrics['accuracy_percent']:.1f}% | R²: {metrics['r2']:.3f}")